Repository pariahstation/Pariah-Station, pull requests merged in 2022-05, with the labels that each got.

#680 Fixes offset features (Alternative to TG)
  code/modules/mob/living/carbon/human/human_update_icons.dm
Labels: Fix

#674 Adds Cryopods (again)
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
Labels: Enhancement, Map Edit

#683 Removes ERP Pref from the code
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/examine_tgui.dm
  modular_pariah/master_files/code/modules/client/preferences/erp_preferences.dm
  tgstation.dme
Labels: AGAINST GOD AND NATURE

#684 Removes more ERP
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/pariah/erp_preference.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/pariah/erp_preferences.tsx
Labels: Fix

#687 Fix skrell hearts
  code/modules/surgery/organs/heart.dm
  icons/obj/surgery.dmi
Labels: Fix

#506 Ports Adds short people, body size options
  code/_globalvars/lists/flavor_misc.dm
  code/datums/dna.dm
  code/modules/client/preferences/body_size.dm
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/character_preferences/body_size.tsx
Labels: Enhancement

#677 Ports screen alerts from TGMC
  code/modules/client/client_defines.dm
  code/modules/screen_alerts/screen_alerts.dm
  tgstation.dme
Labels: Enhancement

#692 Deletes Subtle Code
  code/__DEFINES/~pariah_defines/logging.dm
  code/__HELPERS/_logging.dm
  code/game/atoms.dm
  modular_pariah/master_files/code/modules/verbs/code/modules/client/mob/subtle.dm
  tgstation.dme
Labels: Removal

#679 Sprite accessory split + Hair expansion pack
  code/modules/clothing/head/wig.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/_sprite_accessories.dm
  code/modules/mob/dead/new_player/sprite_accessories/antennae.dm
  code/modules/mob/dead/new_player/sprite_accessories/caps.dm
  code/modules/mob/dead/new_player/sprite_accessories/ears.dm
  code/modules/mob/dead/new_player/sprite_accessories/facial_hair.dm
  code/modules/mob/dead/new_player/sprite_accessories/frills.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair_gradients.dm
  code/modules/mob/dead/new_player/sprite_accessories/headtails.dm
  code/modules/mob/dead/new_player/sprite_accessories/horns.dm
  code/modules/mob/dead/new_player/sprite_accessories/legs.dm
  code/modules/mob/dead/new_player/sprite_accessories/markings.dm
  code/modules/mob/dead/new_player/sprite_accessories/snouts.dm
  code/modules/mob/dead/new_player/sprite_accessories/spines.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  code/modules/mob/dead/new_player/sprite_accessories/underwear.dm
  code/modules/mob/dead/new_player/sprite_accessories/wings.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/ghost.dm
  icons/mob/facial_hair.dmi
  icons/mob/hair.dmi
  icons/mob/human_face.dmi
  tgstation.dme
Labels: Enhancement, Big PR, Refactor

#681 Adds support for character preference tooltips
  tgui/packages/tgui/interfaces/PreferencesMenu/MainPage.tsx
Labels: Enhancement

#694 Moths now have optional colors
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/surgery/bodyparts/species_parts/moth_bodyparts.dm
  icons/mob/species/moth/bodyparts.dmi
Labels: Enhancement

#696 Ports a glass floor bugfix from TG
  code/datums/elements/turf_transparency.dm
  code/game/objects/items/stacks/tiles/light.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/glass.dm
  code/game/turfs/open/floor/plating.dm
  code/modules/mob/living/simple_animal/bot/floorbot.dm
  tgstation.dme
Labels: Fix, Port

#691 Fixes our URL Buttons
  code/controllers/configuration/entries/general.dm
Labels: Fix

#698 Adds more mutant colors
  code/__DEFINES/DNA.dm
  code/__HELPERS/mobs.dm
  code/datums/dna.dm
  code/game/objects/structures/mirror.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences/species_features/mutants.dm
  code/modules/mob/living/carbon/human/species.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
Labels: Enhancement

#697 Ghosts won't see smuggler satchels
  code/game/objects/items/storage/backpack.dm
Labels: Enhancement, Port

#701 Menu sound
  code/_onclick/hud/new_player.dm
  sound/effects/save.ogg
Labels: Enhancement

#700 More character slots
  code/modules/client/preferences.dm
  tgui/packages/tgui/interfaces/PreferencesMenu/CharacterPreferenceWindow.tsx
Labels: Enhancement

#702 Fixes false walls using the old wall sprites
  code/game/turfs/closed/walls.dm
  icons/turf/walls/reinforced_wall.dmi
  icons/turf/walls/wall.dmi
  modular_pariah/modules/aesthetics/walls/code/walls.dm
  modular_pariah/modules/aesthetics/walls/icons/reinforced_wall.dmi
  modular_pariah/modules/aesthetics/walls/icons/wall.dmi
  tgstation.dme
Labels: Fix

#705 Reimplementation of lethal shotgun ammo to security
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/research/designs/autolathe_designs.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Balance

#707 Camera Flash
  code/modules/assembly/flash.dm
  code/modules/uplink/uplink_items/stealthy.dm
Labels: Enhancement, Port

#714 Fixes bar customer robots infinitely looping
  code/modules/food_and_drinks/restaurant/customers/_customer.dm
  code/modules/food_and_drinks/restaurant/generic_venues.dm
Labels: Fix, Port

#720 [READY] Adjusts Species Dummy Colors
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/skrell.dm
Labels: Enhancement

#719 Removes a couple of duplicate loadout entries
  modular_pariah/modules/loadouts/loadout_items/loadout_datum_heads.dm
  modular_pariah/modules/loadouts/loadout_items/loadout_datum_suit.dm
Labels: Fix

#708 chirp chip, adding two chirp emotes, chirp chirp
  code/modules/mob/living/emote.dm
  sound/voice/bird/chirp.ogg
  sound/voice/bird/chirp2.ogg
Labels: Enhancement, Good first PR

#709 Small Lizardpeople/Mothpeople > Unathi/Gamuioda adjustment
  code/datums/components/crafting/guncrafting.dm
  code/datums/elements/weapon_description.dm
  code/datums/mutations/actions.dm
  code/datums/ruins/lavaland.dm
  code/game/objects/effects/contraband.dm
  code/game/objects/effects/spawners/random/clothing.dm
  code/game/objects/items/food/lizard.dm
  code/game/objects/items/food/meat.dm
  code/game/objects/items/plushes.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/weaponry.dm
  code/modules/antagonists/traitor/objectives/sleeper_protocol.dm
  code/modules/cargo/bounties/assistant.dm
  code/modules/cargo/bounties/medical.dm
  code/modules/cargo/bounties/mining.dm
  code/modules/cargo/exports/organs.dm
  code/modules/cargo/exports/sheets.dm
  code/modules/events/sentience.dm
  code/modules/food_and_drinks/drinks/drinks/bottle.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_drink.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/holiday/holidays.dm
  code/modules/instruments/items.dm
  code/modules/language/draconic.dm
  code/modules/language/moffic.dm
  code/modules/mapfluff/ruins/lavalandruin_code/elephantgraveyard.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/research/designs/limbgrower_designs.dm
  code/modules/research/designs/medical_designs.dm
  code/modules/research/techweb/all_nodes.dm
  code/modules/surgery/advanced/wingreconstruction.dm
  code/modules/surgery/organs/tails.dm
  code/modules/vending/wardrobes.dm
  strings/ion_laws.json
  strings/medieval_replacement.json
  strings/phobia.json
  strings/redpill.json
  strings/tcg/set_one.json
  strings/valentines.json
  strings/wanted_message.json
Labels: Enhancement

#723 Adds a Pariah Station shuttle arrivals sound
  code/game/area/areas/shuttles.dm
  sound/voice/ApproachingPariah.ogg
  sound/voice/ApproachingTG.ogg
Labels: Enhancement, Sound

#725 Murders SSDecay
  config/pariah/pariah_config.txt
  modular_pariah/master_files/code/controllers/configuration/entries/pariah_config_entries.dm
  modular_pariah/modules/decay_subsystem/code/decaySS.dm
  modular_pariah/modules/decay_subsystem/code/decay_turf_handling.dm
  tgstation.dme
Labels: Removal

#718 Fixes the HoS not having `ACCESS_SECURITY`
  code/datums/id_trim/jobs.dm
  icons/obj/card.dmi
  modular_pariah/master_files/code/datums/id_trim/jobs.dm
  modular_pariah/master_files/icons/obj/card.dmi
  tgstation.dme
Labels: Fix, Refactor

#727 Colours and annotations for unit test failures
  .github/workflows/ci_suite.yml
  code/modules/error_handler/error_handler.dm
  code/modules/unit_tests/README.md
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/achievements.dm
  code/modules/unit_tests/anchored_mobs.dm
  code/modules/unit_tests/bespoke_id.dm
  code/modules/unit_tests/card_mismatch.dm
  code/modules/unit_tests/chain_pull_through_space.dm
  code/modules/unit_tests/chat_filter.dm
  code/modules/unit_tests/circuit_component_category.dm
  code/modules/unit_tests/closets.dm
  code/modules/unit_tests/component_tests.dm
  code/modules/unit_tests/crayons.dm
  code/modules/unit_tests/create_and_destroy.dm
  code/modules/unit_tests/designs.dm
  code/modules/unit_tests/dynamic_ruleset_sanity.dm
  code/modules/unit_tests/egg_glands.dm
  code/modules/unit_tests/food_edibility_check.dm
  code/modules/unit_tests/greyscale_config.dm
  code/modules/unit_tests/heretic_knowledge.dm
  code/modules/unit_tests/heretic_rituals.dm
  code/modules/unit_tests/hydroponics_harvest.dm
  code/modules/unit_tests/keybinding_init.dm
  code/modules/unit_tests/merge_type.dm
  code/modules/unit_tests/mob_spawn.dm
  code/modules/unit_tests/modular_map_loader.dm
  code/modules/unit_tests/objectives.dm
  code/modules/unit_tests/outfit_sanity.dm
  code/modules/unit_tests/paintings.dm
  code/modules/unit_tests/plantgrowth_tests.dm
  code/modules/unit_tests/preference_species.dm
  code/modules/unit_tests/preferences.dm
  code/modules/unit_tests/projectiles.dm
  code/modules/unit_tests/quirks.dm
  code/modules/unit_tests/rcd.dm
  code/modules/unit_tests/reagent_id_typos.dm
  code/modules/unit_tests/reagent_names.dm
  code/modules/unit_tests/reagent_recipe_collisions.dm
  code/modules/unit_tests/say.dm
  code/modules/unit_tests/security_officer_distribution.dm
  code/modules/unit_tests/species_config_sanity.dm
  code/modules/unit_tests/species_unique_id.dm
  code/modules/unit_tests/species_whitelists.dm
  code/modules/unit_tests/stack_singular_name.dm
  code/modules/unit_tests/subsystem_init.dm
  code/modules/unit_tests/surgeries.dm
  code/modules/unit_tests/timer_sanity.dm
  code/modules/unit_tests/traitor.dm
  code/modules/unit_tests/unit_test.dm
Labels: Port, Github

#733 CI tests for every station instead of just Meta
  .github/workflows/ci_suite.yml
  _maps/RandomRuins/SpaceRuins/spacehotel.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/debug/multiz.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__HELPERS/_logging.dm
  code/modules/holodeck/computer.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/create_and_destroy.dm
  code/modules/unit_tests/mapping.dm
  code/modules/unit_tests/unit_test.dm
  tools/ci/run_server.sh
Labels: Fix, Map edit, Github

#731 Ports cardshark PR from TG
  _maps/shuttles/whiteship_delta.dmm
  code/__DEFINES/memory_defines.dm
  code/_globalvars/lists/maintenance_loot.dm
  code/_globalvars/phobias.dm
  code/datums/mood_events/generic_negative_events.dm
  code/datums/mood_events/generic_positive_events.dm
  code/game/objects/effects/spawners/random/entertainment.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/cards/cardhand.dm
  code/modules/cards/cards.dm
  code/modules/cards/deck/blank.dm
  code/modules/cards/deck/cas.dm
  code/modules/cards/deck/deck.dm
  code/modules/cards/deck/kotahi.dm
  code/modules/cards/deck/tarot.dm
  code/modules/cards/deck/wizoff.dm
  code/modules/cards/singlecard.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/events/holiday/vday.dm
  code/modules/games/cas.dm
  code/modules/games/kotahi.dm
  code/modules/games/tarot.dm
  code/modules/games/wizoff.dm
  code/modules/holodeck/holo_effect.dm
  code/modules/holodeck/items.dm
  code/modules/mob/living/simple_animal/guardian/guardian.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/unit_tests/create_and_destroy.dm
  code/modules/vending/games.dm
  icons/obj/playing_cards.dmi
  icons/obj/toy.dmi
  sound/items/cardflip.ogg
  strings/cas_white.txt
  strings/memories.json
  strings/tips.txt
  tgstation.dme
Labels: Enhancement, Merge Conflict, Port

#736 Fixes Goliath movement
  code/controllers/subsystem/movement/move_handler.dm
  code/controllers/subsystem/movement/movement_types.dm
Labels: Fix, Port

#724 Parallax but better: Smooth movement cleanup TG Port
  code/__DEFINES/dcs/signals/signals_client.dm
  code/_onclick/hud/parallax.dm
  code/datums/components/connect_mob_behalf.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/anomalies.dm
  code/game/objects/effects/temporary_visuals/projectiles/projectile_effects.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/structures/industrial_lift.dm
  code/game/shuttle_engines.dm
  code/modules/art/statues.dm
  code/modules/atmospherics/machinery/components/tank.dm
  code/modules/cargo/supplypod.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mapfluff/ruins/lavalandruin_code/surface.dm
  code/modules/mob/living/silicon/ai/freelook/cameranet.dm
  code/modules/shuttle/docking.dm
  code/modules/station_goals/bsa.dm
  tgstation.dme
Labels: Fix, Enhancement, Port, Testmerge Deployed

#699 Fixes LOOC
  code/__DEFINES/admin.dm
  code/_globalvars/configuration.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/server.dm
  code/modules/client/client_procs.dm
  code/modules/client/verbs/looc.dm
  code/modules/client/verbs/ooc.dm
  modular_pariah/master_files/code/_globalvars/configuration.dm
  modular_pariah/master_files/code/modules/verbs/code/modules/client/looc.dm
  tgstation.dme
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Fix, Enhancement, Port

#742 HOLY SHIT SHUT UP
  modular_pariah/modules/aesthetics/computer/code/computer.dm
Labels: Sound

#722 The Return of Pubby Station
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/pubbystation.json
  config/maps.txt
Labels: Enhancement, Big PR, Map edit, Port, Testmerge Deployed
