Repository pariahstation/Pariah-Station, pull requests merged in 2022-06, with the labels that each got.

#743 Fixes Teshari husk sprites
  code/modules/surgery/bodyparts/species_parts/teshari_bodyparts.dm
  icons/mob/species/teshari/bodyparts.dmi
Labels: Fix, Sprites

#747 Update Gamuioda (Moth's) Lore
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
Labels: Enhancement

#749 Makes tablets get names when not spawned on the belt (#66524)
  code/modules/jobs/job_types/_job.dm
Labels: Fix

#751 Fixes a small buildmode runtime
  code/modules/buildmode/submodes/advanced.dm
  code/modules/buildmode/submodes/basic.dm
Labels: Fix

#752 Snaps Combat Indicator
  code/__DEFINES/~pariah_defines/signals.dm
  code/modules/mob/living/death.dm
  code/modules/vehicles/mecha/_mecha.dm
  modular_pariah/modules/indicators/code/combat_indicator.dm
  modular_pariah/modules/indicators/code/sealed.dm
  modular_pariah/modules/indicators/readme.md
  pariah.dme
Labels: Removal

#737 Discord Verification System
  code/_onclick/hud/new_player.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/discord.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/discord/accountlink.dm
  code/modules/discord/discord_helpers.dm
  code/modules/discord/discord_link_record.dm
  code/modules/discord/discord_sql_functions.dm
  code/modules/discord/tgs_commands.dm
  code/modules/discord/toggle_notify.dm
  code/modules/interview/interview.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/mob/dead/new_player/new_player.dm
  config/config.txt
  pariah.dme
  strings/eff_large_wordlist.txt
Labels: Enhancement, Port, Testmerge Deployed

#754 Removes tail pulling
  code/datums/mood_events/generic_positive_events.dm
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Enhancement

#678 Revert "[SEMI MODULAR] Ports the IC Spawning Module from SR"
  code/modules/admin/admin_verbs.dm
  modular_pariah/modules/icspawning/code/admin_procs.dm
  modular_pariah/modules/icspawning/code/spell.dm
  modular_pariah/modules/icspawning/readme.md
  pariah.dme
Labels: Merge Conflict, BYOND BUG, RED LABEL

#757 Fixes donuts sometimes not having an icon state
  code/game/objects/items/food/donuts.dm
Labels: Fix

#738 Unit test log cleanup
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/idlenpcpool.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/npcpool.dm
  code/datums/map_config.dm
  code/modules/antagonists/blob/structures/core.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/power/apc/apc_main.dm
  code/modules/projectiles/guns/energy/laser_gatling.dm
  code/modules/unit_tests/load_map_security.dm
Labels: Refactor, Github

#744 Adds a lightswitch button to the APC UI
  code/modules/power/apc/apc_main.dm
  tgui/packages/tgui/interfaces/Apc.js
Labels: Enhancement, Testmerge Deployed

#734 Re-adds the Deluxe Agent Card
  code/modules/uplink/uplink_items/stealthy_tools.dm
Labels: Enhancement, Balance, Testmerge Deployed

#760 Small vox fixes or something
  code/__HELPERS/names.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#729 Mob holding refactor
  code/__DEFINES/is_helpers.dm
  code/datums/components/storage/concrete/pockets.dm
  code/datums/status_effects/debuffs/debuffs.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/clothing/clothing.dm
  code/modules/holodeck/computer.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_stripping.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/teshari.dm
  code/modules/mob/living/inhand_holder.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_stripping.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/pai_shell.dm
  code/modules/mob/living/simple_animal/bot/mulebot.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/mob/living/simple_animal/friendly/dog.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/friendly/drone/interaction.dm
  code/modules/mob/living/simple_animal/friendly/fox.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/rabbit.dm
  code/modules/mob/living/simple_animal/friendly/sloth.dm
  code/modules/mob/living/simple_animal/hostile/ant.dm
  code/modules/mob/living/simple_animal/hostile/bees.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/frog.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/mob.dm
  code/modules/unit_tests/create_and_destroy.dm
  icons/mob/animal_item_head.dmi
  icons/mob/pai_item_head.dmi
  icons/mob/pets_held.dmi
  pariah.dme
  strings/tips.txt
Labels: Refactor, Testmerge Deployed

#763 Fixes another random CI failure
  code/__HELPERS/turfs.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/get_turf_pixel.dm
Labels: Fix, Port

#759 Fixes a small playing card runtime
  code/modules/cards/cardhand.dm
Labels: Fix, Port

#761 Small Teshari tweaks/fixes part 2
  code/modules/mob/living/carbon/human/species_types/teshari.dm
  code/modules/surgery/organs/external/_external_organs.dm
Labels: Fix

#745 Species examine text
  code/modules/antagonists/nightmare/nightmare_species.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/abductors.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/human/species_types/dullahan.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/golems.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/human/species_types/mushpeople.dm
  code/modules/mob/living/carbon/human/species_types/shadowpeople.dm
  code/modules/mob/living/carbon/human/species_types/skeletons.dm
  code/modules/mob/living/carbon/human/species_types/skrell.dm
  code/modules/mob/living/carbon/human/species_types/snail.dm
  code/modules/mob/living/carbon/human/species_types/vampire.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
Labels: Enhancement

#764 Tablets now have a crew manifest app by default
  code/datums/datacore.dm
  code/modules/modular_computers/hardware/hard_drive.dm
Labels: Enhancement

#766 New IPC (eventually) / PAI cable sprite
  icons/obj/power.dmi
Labels: Port, Sprites

#765 Fixes Vox sprites and cleans up some render code
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  code/modules/mob/living/carbon/human/species_types/vox.dm
  code/modules/surgery/bodyparts/species_parts/vox_bodyparts.dm
  icons/mob/clothing/species/vox/feet.dmi
Labels: Fix

#768 Fixes items disappearing in the suit storage slot
  code/modules/mob/living/carbon/human/human_update_icons.dm
Labels: Fix

#781 Girder/wall hiddenprints fix
  code/game/objects/structures/girders.dm
Labels: Fix

#779 More customization (side frills + broken horns)
  code/modules/mob/dead/new_player/sprite_accessories/frills.dm
  code/modules/mob/dead/new_player/sprite_accessories/horns.dm
  icons/mob/mutant_bodyparts.dmi
Labels: Enhancement, Port

#774 Fixes the thermomachine error sprite
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
Labels: Fix

#771 Formatting
  code/__HELPERS/mobs.dm
  code/datums/components/embedded.dm
  code/datums/components/pellet_cloud.dm
  code/datums/wounds/_wounds.dm
  code/datums/wounds/bones.dm
  code/datums/wounds/burns.dm
  code/datums/wounds/pierce.dm
  code/datums/wounds/slash.dm
  code/game/machinery/limbgrower.dm
  code/game/objects/items/devices/scanners/health_analyzer.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/antagonists/abductor/equipment/glands/heal.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/android.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/head.dm
  code/modules/surgery/bodyparts/parts.dm
Labels: Enhancement

#790 Tramstation moment, fixes checks
  _maps/map_files/tramstation/modular_pieces/maintenance_science_west_attachment_3.dmm
Labels: Fix, Port

#789 Adds Round Time and Alert Level to Hub entry Port
  code/game/world.dm
Labels: Enhancement, Port

#783 Github Actions-based Changelog Building
  .github/workflows/compile_changelogs.yml
  .github/workflows/make_changelogs.yml
  tools/changelog/generate_cl.py
  tools/changelog/makeChangelog.bat
  tools/changelog/requirements.txt
  tools/changelog/ss13_genchangelog.py
  tools/changelog/tags.yml
  tools/ci/check_changelogs.sh
Labels: Github

#793 Allow toggling holiday floor fuckery
  code/controllers/configuration/entries/general.dm
  code/game/objects/effects/decals/turfdecal/tilecoloring.dm
  config/config.txt
Labels: Enhancement

#794 Adds all previous PR changelogs
  html/changelogs/archive/2022-03.yml
  html/changelogs/archive/2022-04.yml
  html/changelogs/archive/2022-05.yml
  html/changelogs/archive/2022-06.yml
Labels: Enhancement

#776 Various Vox tweaks
  code/__DEFINES/mobs.dm
  code/game/objects/items/tanks/n2_tanks.dm
  code/modules/client/preferences/species_features/vox.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/outfits/vox.dm
  code/modules/language/language_manuals.dm
  code/modules/language/vox.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair.dm
  code/modules/mob/living/carbon/human/species_types/vox.dm
  icons/misc/language.dmi
  icons/mob/inhands/equipment/tanks_lefthand.dmi
  icons/mob/inhands/equipment/tanks_righthand.dmi
  icons/obj/clothing/masks.dmi
Labels: Enhancement

#770 Blood Brothers, Thief, and Opportunist antag icon fixes
  code/modules/antagonists/brother/brother.dm
  code/modules/antagonists/thief/thief.dm
Labels: Fix

#767 Adds a Vox Description
  code/modules/mob/living/carbon/human/species_types/vox.dm
Labels: Enhancement, Testmerge Deployed

#772 Fixes a runtime error from hydroponics trays
  code/modules/hydroponics/hydroponics.dm
Labels: Fix

#787 Gamuioda (Moth) head shape update: They actually look like bugs now, woah.
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  icons/mob/human_face.dmi
  icons/mob/species/moth/bodyparts.dmi
  icons/mob/species/moth/eyes.dmi
Labels: Sprites, Testmerge Deployed

#791 Adds a 'Set all lights' admin secret
  code/modules/admin/verbs/secrets.dm
  tgui/packages/tgui/interfaces/Secrets.js
Labels: Enhancement

#777 Shuttle smoothing improvements
  code/__DEFINES/icon_smoothing.dm
  code/__HELPERS/icon_smoothing.dm
  code/game/objects/structures/false_walls.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed/wall/mineral_walls.dm
  code/game/turfs/closed/walls.dm
Labels: Fix, Enhancement, Testmerge Deployed

#801 Host sanctioned emote spamming, or, audible *scream emote
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/vox.dm
Labels: Enhancement

#798 Bandana stuff port
  _maps/RandomRuins/LavaRuins/lavaland_surface_elephant_graveyard.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  code/datums/components/crafting/tailoring.dm
  code/game/machinery/washing_machine.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/antagonists/gang/gang.dm
  code/modules/antagonists/thief/thief.dm
  code/modules/cargo/packs.dm
  code/modules/clothing/masks/bandana.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/mob/living/simple_animal/friendly/trader.dm
  code/modules/vending/clothesmate.dm
  code/modules/vending/wardrobes.dm
Labels: Enhancement, Port, Sprites
