Repository pariahstation/Pariah-Station, pull requests merged in 2022-07, with the labels that each got.

#786 NSV Parallax Port
  code/_onclick/hud/parallax.dm
  icons/effects/parallax.dmi
Labels: Port, Sprites, Testmerge Deployed

#792 Most likely not how this works, but, clothing fitting, less human sprites on less conventionally humanoid species
  code/datums/greyscale/config_types/greyscale_configs.dm
  code/datums/greyscale/json_configs/bandana.json
  code/datums/greyscale/json_configs/bandana_up.json
  code/datums/greyscale/json_configs/bandana_worn.json
  code/datums/greyscale/json_configs/bandana_worn_up.json
  code/datums/greyscale/json_configs/bandskull.json
  code/datums/greyscale/json_configs/bandskull_up.json
  code/datums/greyscale/json_configs/bandskull_worn.json
  code/datums/greyscale/json_configs/bandskull_worn_up.json
  code/datums/greyscale/json_configs/bandstriped.json
  code/datums/greyscale/json_configs/bandstriped_up.json
  code/datums/greyscale/json_configs/bandstriped_worn.json
  code/datums/greyscale/json_configs/bandstriped_worn_up.json
  code/game/objects/items/holy_weapons.dm
  code/modules/clothing/masks/bandana.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/suits/_suits.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/costume.dm
  code/modules/clothing/suits/jacket.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/moth.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/costume.dm
  code/modules/clothing/under/jobs/cargo.dm
  code/modules/clothing/under/jobs/centcom.dm
  code/modules/clothing/under/jobs/civilian/civilian.dm
  code/modules/clothing/under/jobs/civilian/clown_mime.dm
  code/modules/clothing/under/jobs/civilian/curator.dm
  code/modules/clothing/under/jobs/command.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medical.dm
  code/modules/clothing/under/jobs/rnd.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/shorts.dm
  code/modules/clothing/under/skirt_dress.dm
  code/modules/clothing/under/suits.dm
  code/modules/clothing/under/syndicate.dm
  icons/mob/clothing/species/vox/color_gags_vox.dmi
  icons/mob/clothing/species/vox/head.dmi
  modular_pariah/modules/customization/modules/clothing/clothing.dm
Labels: Fix, Sprites

#796 Updates antagonist Dummy's
  code/modules/antagonists/creep/creep.dm
  code/modules/antagonists/revolution/revolution.dm
  code/modules/antagonists/traitor/datum_traitor.dm
Labels: Enhancement

#799 Updates Skrell and Vox Language Icon
  icons/misc/language.dmi
Labels: Fix, Sprites, Testmerge Deployed

#810 Removes gun safeties
  code/modules/unit_tests/projectiles.dm
  modular_pariah/master_files/code/modules/projectiles/guns/gun.dm
  modular_pariah/modules/gunsafety/code/gun_safety.dm
  modular_pariah/modules/gunsafety/icons/actions.dmi
  modular_pariah/modules/gunsafety/readme.md
  pariah.dme
Labels: Removal

#812 More Skrell customization, colorable headtails
  code/modules/client/preferences/species_features/skrell.dm
  code/modules/mob/dead/new_player/sprite_accessories/headtails.dm
  code/modules/mob/living/carbon/human/species_types/skrell.dm
Labels: Enhancement

#811 Fixes skrell having a nose/moustache something
  icons/mob/species/skrell/bodyparts.dmi
Labels: Fix

#695 Adds Fax Machines from Jollystation
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/IceBoxStation/IcemoonUnderground_Above.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/__DEFINES/paperwork_defines.dm
  code/__DEFINES/wires.dm
  code/__HELPERS/text.dm
  code/controllers/subsystem/economy.dm
  code/datums/wires/fax.dm
  code/game/machinery/fax_machine.dm
  code/modules/admin/topic.dm
  code/modules/paperwork/paper.dm
  icons/obj/machines/fax.dmi
  pariah.dme
  strings/paperwork.json
  tgui/packages/tgui/interfaces/FaxMachine.js
Labels: Enhancement, Map edit, Port

#813 Small changelog hyperlink removal
  html/changelogs/archive/2022-07.yml
Labels: Fix

#821 Fixes black skrell headtails in their species preview
  code/modules/mob/living/carbon/human/species_types/skrell.dm
Labels: Fix

#730 Baystation airlock sounds
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/shutters.dm
  modular_pariah/modules/aesthetics/airlock/code/airlock.dm
  sound/machines/doors/airlock_close.ogg
  sound/machines/doors/airlock_close_force.ogg
  sound/machines/doors/airlock_open.ogg
  sound/machines/doors/airlock_open_force.ogg
  sound/machines/doors/blastdoor_close.ogg
  sound/machines/doors/blastdoor_open.ogg
  sound/machines/doors/shutters_close.ogg
  sound/machines/doors/shutters_open.ogg
Labels: Port, Sound

#780 A little something special for AIs.
  code/game/machinery/computer/robot.dm
  code/modules/antagonists/traitor/equipment/Malf_Modules.dm
  sound/ai/malf_showboat.ogg
Labels: Enhancement, Sound, Testmerge Deployed

#818 Softens up the lighting to create more depth
  code/modules/power/lighting/light.dm
Labels: Enhancement

#814 Updates the player ticket panel (TG port)
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/client/client_procs.dm
  modular_pariah/modules/admin/code/admin_help.dm
  modular_pariah/modules/admin/code/adminhelp.dm
  pariah.dme
Labels: Refactor, Port

#803 More immersive ambience
  code/_globalvars/lists/ambience.dm
  code/controllers/subsystem/ambience.dm
  code/game/area/areas.dm
  code/game/area/areas/mining.dm
  code/game/area/areas/ruins/_ruins.dm
  code/game/area/areas/ruins/lavaland.dm
  code/game/area/space_station_13_areas.dm
  code/modules/power/apc/apc_power_proc.dm
  sound/ambience/Cave1.ogg
  sound/ambience/cavesound3.ogg
  sound/ambience/magma.ogg
  sound/ambience/maintambience.ogg
  sound/ambience/source_corridor2.ogg
  sound/ambience/source_holehit3.ogg
Labels: Enhancement, Sound, Testmerge Deployed

#740 Alternate job outfits for species and alt job titles
  code/modules/client/preferences/middleware/jobs.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/paramedic.dm
  code/modules/jobs/job_types/prisoner.dm
  code/modules/jobs/job_types/psychologist.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/ethereal.dm
  code/modules/mob/living/carbon/human/species_types/flypeople.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/lizardpeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/species_types/plasmamen.dm
  code/modules/mob/living/carbon/human/species_types/podpeople.dm
  code/modules/mob/living/carbon/human/species_types/skrell.dm
  code/modules/mob/living/simple_animal/hostile/zombie.dm
  code/modules/vending/wardrobes.dm
  icons/mob/clothing/species/teshari/suit.dmi
  icons/mob/clothing/species/teshari/uniform.dmi
  icons/mob/clothing/species/vox/uniform.dmi
  icons/mob/clothing/suit.dmi
  icons/mob/clothing/under/engineering.dmi
  icons/mob/species/misc/digitigrade.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/under/engineering.dmi
  modular_pariah/master_files/code/modules/mob/dead/new_player/preferences_setup.dm
Labels: Enhancement, Good first PR, Testmerge Deployed

#686 Adds modded humans
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/modder.dm
  config/game_options.txt
  pariah.dme
Labels: Enhancement, Testmerge Needed

#816 3/4ifies centcom and some indestructible walls
  _maps/RandomRuins/IceRuins/icemoon_surface_lust.dmm
  _maps/RandomRuins/IceRuins/icemoon_underground_mailroom.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_ash_walker1.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_cube.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_gluttony.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_hierophant.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_pride.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_sloth.dmm
  _maps/RandomRuins/LavaRuins/lavaland_surface_wizard.dmm
  _maps/RandomRuins/SpaceRuins/TheDerelict.dmm
  _maps/RandomRuins/SpaceRuins/forgottenship.dmm
  _maps/RandomRuins/SpaceRuins/hellfactory.dmm
  _maps/RandomRuins/SpaceRuins/hilbertresearchfacility.dmm
  _maps/RandomZLevels/SnowCabin.dmm
  _maps/RandomZLevels/undergroundoutpost45.dmm
  _maps/map_files/CTF/classic.dmm
  _maps/map_files/CTF/cruiser.dmm
  _maps/map_files/CTF/fourSide.dmm
  _maps/map_files/CTF/limbo.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/Mafia/mafia_ayylmao.dmm
  _maps/map_files/Mafia/mafia_ball.dmm
  _maps/map_files/Mafia/mafia_gothic.dmm
  _maps/map_files/Mafia/mafia_lavaland.dmm
  _maps/map_files/Mafia/mafia_snow.dmm
  _maps/map_files/Mafia/mafia_spiderclan.dmm
  _maps/map_files/Mafia/mafia_syndie.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/Mining/Lavaland.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/tramstation/tramstation.dmm
  _maps/shuttles/emergency_luxury.dmm
  _maps/templates/admin_thunderdome.dmm
  _maps/templates/heretic_sacrifice_template.dmm
  code/__DEFINES/icon_smoothing.dm
  code/datums/materials/basemats.dm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/closed/wall/mineral_walls.dm
Labels: Enhancement
