Repository pariahstation/Pariah-Station, pull requests merged in 2022-04, with the labels that each got.

#143 Modular Cryopods
  code/game/gamemodes/objective.dm
  code/game/machinery/announcement_system.dm
  modular_pariah/modules/cryosleep/code/ai.dm
  modular_pariah/modules/cryosleep/code/cryopod.dm
  modular_pariah/modules/cryosleep/code/job.dm
  modular_pariah/modules/cryosleep/code/mind.dm
  modular_pariah/modules/cryosleep/icons/cryogenics.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/CryopodConsole.js
Labels: Semi modular

#152 Adds Upgrades to Drink Machines and New Drinks
  code/__DEFINES/~pariah_defines/DNA.dm
  code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/plumbing/plumbers/pill_press.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  modular_pariah/modules/customization/modules/food_and_drinks/recipes/drink_recipes.dm
  modular_pariah/modules/customization/modules/reagents/chemistry/reagents.dm
  modular_pariah/modules/customization/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  tgstation.dme
Labels: Enhancement, Semi modular, WIP

#219 Implements kapulimbs digi handling for clothes + loadout audit
  code/__DEFINES/inventory.dm
  code/__DEFINES/species_clothing_paths.dm
  code/game/objects/items.dm
  code/modules/clothing/shoes/sneakers.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/mob/living/carbon/human/human_update_icons.dm
  modular_pariah/master_files/code/modules/mod/mod_clothes.dm
  modular_pariah/master_files/code/modules/mod/modules/mod.dm
  modular_pariah/master_files/code/modules/mod/modules/modules_antag.dm
  modular_pariah/master_files/icons/mob/clothing/feet.dmi
  modular_pariah/master_files/icons/mob/clothing/feet_digi.dmi
  modular_pariah/master_files/icons/mob/mod.dmi
  modular_pariah/master_files/icons/obj/clothing/shoes.dmi
  modular_pariah/modules/GAGS/greyscale_configs.dm
  modular_pariah/modules/GAGS/icons/sneakers_digi.dmi
  modular_pariah/modules/customization/modules/clothing/clothing.dm
  modular_pariah/modules/customization/modules/clothing/head/head.dm
  modular_pariah/modules/customization/modules/clothing/neck/cloaks.dm
  modular_pariah/modules/customization/modules/clothing/shoes/shoes.dm
  modular_pariah/modules/customization/modules/clothing/suits/armor.dm
  modular_pariah/modules/customization/modules/clothing/suits/coats.dm
  modular_pariah/modules/customization/modules/clothing/suits/hoodies.dm
  modular_pariah/modules/customization/modules/clothing/suits/misc.dm
  modular_pariah/modules/customization/modules/clothing/suits/trek.dm
  modular_pariah/modules/customization/modules/clothing/under/costumes.dm
  modular_pariah/modules/customization/modules/clothing/under/misc.dm
  modular_pariah/modules/customization/modules/clothing/under/security.dm
  modular_pariah/modules/customization/modules/clothing/under/suits.dm
  modular_pariah/modules/customization/modules/clothing/under/sweaters.dm
  modular_pariah/modules/customization/modules/clothing/under/trek.dm
  modular_pariah/modules/customization/modules/clothing/under/utility_port/suits_port.dm
  modular_pariah/modules/loadouts/loadout_items/loadout_datum_heads.dm
  modular_pariah/modules/loadouts/loadout_items/loadout_datum_shoes.dm
  modular_pariah/modules/loadouts/loadout_items/loadout_datum_suit.dm
  tgstation.dme
Labels: Enhancement, Semi modular

#347 Alternate job titles
  code/__DEFINES/~pariah_defines/span.dm
  code/controllers/subsystem/job.dm
  code/datums/datacore.dm
  code/modules/client/preferences/middleware/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  interface/stylesheet.dm
  modular_pariah/master_files/code/modules/client/preferences.dm
  modular_pariah/master_files/code/modules/client/preferences_savefile.dm
  modular_pariah/modules/alternative_job_titles/code/alt_job_titles.dm
  modular_pariah/modules/alternative_job_titles/code/job.dm
  modular_pariah/modules/alternative_job_titles/readme.md
  tgstation.dme
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui/interfaces/CrewManifest.js
  tgui/packages/tgui/interfaces/NtosCrewManifest.js
  tgui/packages/tgui/interfaces/PreferencesMenu/JobsPage.tsx
  tgui/packages/tgui/interfaces/PreferencesMenu/data.ts
  tgui/packages/tgui/styles/interfaces/PreferencesMenu.scss
Labels: Enhancement, Completely original modularisation, Semi modular

#373 Completely fixes Default input (shiptest-ss13/Shiptest#508)
  code/controllers/subsystem/input.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences/hotkeys.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/keybindings/setup.dm
  config/admins.txt
Labels: Fix, Modular, Enhancement, Good first PR

#405 Master ERP pref no longer shows up as error
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/pariah/erp_preferences.tsx
Labels: Fix

#490 Adds Cryopods
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/IceBoxStation/IceBoxStation.dmm
  _maps/map_files/KiloStation/KiloStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/tramstation/tramstation.dmm
  code/game/area/space_station_13_areas.dm
Labels: Not modular, Good first PR

#577 Actually makes our config work, puts it in a better place
  config/config.txt
  config/pariah/pariah_config.txt
Labels: Fix

#566 [NOT MODULAR] Fancy Chat Blocks
  code/datums/components/mood.dm
  code/datums/elements/weapon_description.dm
  code/datums/mind.dm
  code/game/atoms.dm
  code/modules/mob/living/carbon/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/silicon/ai/examine.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
  code/modules/mob/living/simple_animal/guardian/types/dextrous.dm
  code/modules/mob/living/simple_animal/slime/slime.dm
  code/modules/mob/mob.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Enhancement

#564 [SEMI-MODULAR]Old Baystation Announcer
  code/controllers/subsystem/processing/station.dm
  modular_pariah/modules/announcer/code/baystation_announcer.dm
  modular_pariah/modules/announcer/readme.md
  modular_pariah/modules/announcer/sound/aliens.ogg
  modular_pariah/modules/announcer/sound/attention.ogg
  modular_pariah/modules/announcer/sound/commandreport.ogg
  modular_pariah/modules/announcer/sound/granomalies.ogg
  modular_pariah/modules/announcer/sound/intercept.ogg
  modular_pariah/modules/announcer/sound/ionstorm.ogg
  modular_pariah/modules/announcer/sound/meteors.ogg
  modular_pariah/modules/announcer/sound/outbreak5.ogg
  modular_pariah/modules/announcer/sound/outbreak7.ogg
  modular_pariah/modules/announcer/sound/poweroff.ogg
  modular_pariah/modules/announcer/sound/poweron.ogg
  modular_pariah/modules/announcer/sound/radiation.ogg
  modular_pariah/modules/announcer/sound/shuttlecalled_static.ogg
  modular_pariah/modules/announcer/sound/shuttledock.ogg
  modular_pariah/modules/announcer/sound/shuttlerecalled.ogg
  modular_pariah/modules/announcer/sound/spanomalies.ogg
  modular_pariah/modules/announcer/sound/welcome.ogg
  tgstation.dme
Labels: Enhancement, Semi modular

#526 [SEMI-MODULAR] Autotransfer Port
  code/controllers/subsystem/vote.dm
  code/modules/shuttle/emergency.dm
  config/pariah/pariah_config.txt
  modular_pariah/master_files/code/controllers/configuration/entries/pariah_config_entries.dm
  modular_pariah/modules/autotransfer/code/autotransfer.dm
  modular_pariah/modules/autotransfer/code/shuttle.dm
  modular_pariah/modules/autotransfer/readme.md
  tgstation.dme
Labels: Enhancement, Upstream mirror, Completely original modularisation, Semi modular

#505 [SEMI MODULAR] Ports the Admin module from SR (LoudAsay, Pie Smite, Ticket Handling)
  code/modules/admin/admin_verbs.dm
  code/modules/admin/sql_ban_system.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
  modular_pariah/modules/admin/code/admin_help.dm
  modular_pariah/modules/admin/code/adminhelp.dm
  modular_pariah/modules/admin/code/loud_say.dm
  modular_pariah/modules/admin/code/smites/pie.dm
  modular_pariah/modules/admin/readme.md
  modular_pariah/modules/admin/sound/duckhonk.ogg
  tgstation.dme
Labels: Good first PR, Completely original modularisation, Semi modular

#565 [NOT MODULAR] Throwing Sound and Animation
  code/modules/mob/living/carbon/carbon.dm
Labels: Not modular, Enhancement

#589 [MODULAR] Ports table flipping from skyrat
  modular_pariah/modules/tableflip/code/flipped_table.dm
  modular_pariah/modules/tableflip/icons/flipped_tables.dmi
  tgstation.dme
Labels: Modular, Enhancement, Good first PR

#517 [SEMI MODULAR] Ports the IC Spawning Module from SR
  code/modules/admin/admin_verbs.dm
  modular_pariah/modules/icspawning/code/admin_procs.dm
  modular_pariah/modules/icspawning/code/spell.dm
  modular_pariah/modules/icspawning/readme.md
  tgstation.dme
Labels: Modular, Enhancement, Completely original modularisation

#670 Updates debug verbs
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/commandreport.dm
Labels: Enhancement

#671 Reorganises the 'Status' panel
  code/controllers/subsystem/statpanel.dm
  code/controllers/subsystem/ticker.dm
Labels: Enhancement

#665 Welding Tool Animation
  code/game/objects/items.dm
  code/game/objects/items/tools/weldingtool.dm
  icons/effects/welding_effect.dmi
Labels: Enhancement

#663 Handcuffs and aggro grab restrict you from reaching for comms
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/implants/implant_misc.dm
Labels: Enhancement

#480 Just Skrell, no funny title here
  code/__DEFINES/DNA.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/~pariah_defines/DNA.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/dna.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/admin/create_mob.dm
  code/modules/cargo/packs.dm
  code/modules/client/preferences/species_features/skrell.dm
  code/modules/language/language_holder.dm
  code/modules/language/skrell.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/skrell.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/surgery/bodyparts/species_parts/skrell_bodyparts.dm
  code/modules/surgery/organs/external/_external_organs.dm
  code/modules/surgery/organs/eyes.dm
  code/modules/surgery/organs/heart.dm
  code/modules/surgery/organs/liver.dm
  code/modules/surgery/organs/lungs.dm
  code/modules/surgery/organs/tongue.dm
  config/game_options.txt
  icons/misc/language.dmi
  icons/mob/skrell_headtails.dmi
  icons/mob/species/skrell/bodyparts.dmi
  icons/mob/species/skrell/eyes.dmi
  icons/obj/surgery.dmi
  tgstation.dme
  tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/species_features.tsx
Labels: Enhancement
